USE [FunnettStation]
GO

/****** ÐÂÉ¾ºÚÃûµ¥******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SC_BlackDelCard](
	[ID] [uniqueidentifier] NOT NULL,
	[FUserCardNo] [varchar](16) NOT NULL,
	[FBlackDate] [date] NULL,
 CONSTRAINT [PK_SC_BLACKDELCARD] PRIMARY KEY CLUSTERED 
(
	[FUserCardNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


