USE [FunnettStation]
GO

/****** «π…Ë÷√ ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CS_SetGun](
	[FGUNNO] [int] NOT NULL,
	[FStationCode] [bigint] NULL,
	[FMachineNO] [int] NULL,
	[FGasType] [int] NULL,
	[FphysicalAdress] [int] NULL,
	[FMInfo] [varchar](50) NULL,
 CONSTRAINT [PK_CS_SetGun] PRIMARY KEY CLUSTERED 
(
	[FGUNNO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


